### ISSUE TITLE
Remove previous popup data

### ISSUE THREAD

**Issue by h8rry** [gduck/fritter#52]
Bug reproduction
1. Click on 
![screen shot 2015-02-03 at 11 46 20 am](https://cloud.githubusercontent.com/assets/1697380/6014185/802de914-ab9a-11e4-8393-00748fb96917.png)
1. This shows up
   ![screen shot 2015-02-03 at 11 43 54 am](https://cloud.githubusercontent.com/assets/1697380/6014187/86305ea0-ab9a-11e4-9ee7-0a0ff9f97a1c.png)
2. Close the popup
3. Click on 
   ![screen shot 2015-02-03 at 11 46 23 am](https://cloud.githubusercontent.com/assets/1697380/6014189/8ed478de-ab9a-11e4-816c-b288db8f053e.png)
4. This shows up first (we don't want that)
   ![screen shot 2015-02-03 at 11 43 54 am](https://cloud.githubusercontent.com/assets/1697380/6014192/988e84dc-ab9a-11e4-9f51-70277b4b7b1c.png)
5. Then, the data gets replaces and this shows up
   ![screen shot 2015-02-03 at 11 44 04 am](https://cloud.githubusercontent.com/assets/1697380/6014194/a1da72c6-ab9a-11e4-8762-297f8f1b3528.png)

**Comment by cassiemak** [comment]
I dont seem to have this problem... hmmm  how would you suggest i removing previous popup data
